# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Levi Felling
tagline:          Work & Play
url:              http://levifelling.github.io/
markdown: redcarpet
#paginate:         1
#paginate_path: 	'blog/page:num'
baseurl:          /
author:
  name:           Levi Felling
  url:            https://twitter.com/715elvi
  email:          levifelling@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/levifelling/levifelling.github.com

pages_list:       
  Projects: '/projects'
  Blog: '/blog'
